#!/bin/bash

# Example of bashrc for HYPS on KEKCC


#----- Prompt -----#
export PS1="[\u\[\e[33m\]@\h\[\e[0m\] \W]$ "


#----- Aliases -----#
alias ls='ls -v --color=auto'
alias ll='ls -vlh --color=auto'
alias la='ls -a'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias vi='vim'
alias em='emacs -nw'
alias root='root -l'
alias ta='tmux a'
alias tl='tmux ls'
alias tks='tmux kill-session'


#----- Environment Variables, Setings -----#
export MAKEFLAGS=-j40
export PATH=/group/had/sks/software/unpacker/hyps/bin:$PATH
. /sw/packages/root/6.32.04/bin/thisroot.sh
conda activate myenv

#----- Custom Functions -----#
# ls with cd
cd()
{
builtin cd "$@" && ls
}
