#!/bin/bash

#----- Prompt -----#
export PS1="[\u\[\e[33m\]@\h\[\e[0m\] \W]$ "
export LSCOLORS=gxdxcxbxfxegexabagacad

#----- Aliases -----#
alias ls='ls -v --color=auto'
alias ll='ls -vlh --color=auto'
alias la='ls -a'
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -iv'
alias vi='vim'
alias em='emacs -nw'
alias root='root -l'
alias ta='tmux a'
alias tl='tmux ls'
alias tks='tmux kill-session'

export MAKEFLAGS=-j40

module load gcc/830
module load git/2260
module load python/3.7 2>/dev/null

. /opt/python-3.7/etc/profile.d/conda.sh
conda activate py37

#----- HYPS -----#
export ROOTSYS=/group/had/sks/software/root/6.30.06
source $ROOTSYS/bin/thisroot.sh
export PATH=/group/had/sks/software/unpacker/hyps/bin:$PATH

#----- Custom Functions -----#
# ls with cd
cd()
{
builtin cd "$@" && ls
}

export PATH=/group/had/sks/software/tmux:$PATH
